apiVersion: v1
kind: Service
metadata:
  name: corebos-kubernetes-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: corebos-kubernetes
  ports:
    - port: 80
      targetPort: 80
